set( Boost_NO_BOOST_CMAKE ON )
set( Boost_USE_STATIC_LIBS OFF )
set( Boost_USE_MULTITHREADED ON )
set( Boost_USE_STATIC_RUNTIME OFF )
set( Boost_NO_SYSTEM_PATHS ON )
set( Boost_FIND_QUIETLY ON )
set( BOOST_ROOT ${CMAKE_SOURCE_DIR}/3rd/boost)
MESSAGE(STATUS ${CMAKE_SOURCE_DIR}/3rd/boost)
find_package(Boost COMPONENTS system filesystem regex program_options unit_test_framework)
if(Boost_FOUND)
    include_directories(${Boost_INCLUDE_DIRS})
    link_directories(${Boost_LIBRARY_DIRS})
    MESSAGE(STATUS ${Boost_INCLUDE_DIRS} ${Boost_LIBRARY_DIRS})
endif()
